experiment_type: tree
Architecture:
  class: CatBoostRegressor
  parameters:
    iterations: 2900
    learning_rate: 0.0824603823107217
    depth: 10
    l2_leaf_reg: 0.013717822234815501
    loss_function: RMSE
    verbose: 100
    allow_writing_files: False
Training:
  seed: 42
  dataset_id: Panasonic18650PFData
