experiment_type: nn
Architecture:
  class: ResNet1D
  parameters:
    output_size: 1
    num_filters: 256
    fc_units: 128
    num_res_blocks: 2
    dropout1: 0.16545142820503494
    dropout2: 0.00005242246094255831
Training:
  seed: 42
  dataset_id: Panasonic18650PFData
  dataset_class: SequentialDataset
  batch_size: 256
  num_epochs: 100
  optimizer: Adam
  optimizer_params:
    lr: 0.00135244035571123
  loss_function: MSELoss
