experiment_type: tree
Architecture:
  class: CatBoostRegressor
  parameters:
    iterations: 3000
    learning_rate: 0.07800412516552699
    depth: 8
    l2_leaf_reg: 0.800242972984736
    loss_function: RMSE
    verbose: 100
    allow_writing_files: False
Training:
  seed: 42
  dataset_id: BeijingPM25Quality
