experiment_type: nn
Architecture:
  class: ResNet1D
  parameters:
    output_size: 1
    num_filters: 256
    fc_units: 64
    num_res_blocks: 4
    dropout1: 0.029653270892039528
    dropout2: 0.06029366521701516
Training:
  seed: 42
  dataset_id: BeijingPM25Quality
  dataset_class: SequentialDataset
  batch_size: 256
  num_epochs: 100
  optimizer: Adam
  optimizer_params:
    lr: 0.005613532243174802
  loss_function: MSELoss
