search_space:
  Architecture.parameters.iterations:
    type: int
    low: 500
    high: 3000
    step: 100

  Architecture.parameters.depth:
    type: int
    low: 3
    high: 10

  Architecture.parameters.learning_rate:
    type: float
    low: 0.001
    high: 0.1
    log: true

  Architecture.parameters.l2_leaf_reg:
    type: float
    low: 0.01
    high: 10.0
    log: true