search_space:
  Architecture.parameters.d_model:
    type: categorical
    choices: [64, 128, 256]

  Architecture.parameters.n_heads:
    type: categorical
    choices: [4, 8, 16]

  Architecture.parameters.num_layers:
    type: int
    low: 1
    high: 4

  Architecture.parameters.est_head_dim:
    type: categorical
    choices: [128, 256]

  Architecture.parameters.dropout_rate:
    type: float
    low: 0.0
    high: 0.2

  Architecture.parameters.est_head_dropout:
    type: float
    low: 0.0
    high: 0.2

  Training.optimizer_params.lr:
    type: float
    low: 0.00001
    high: 0.001
    log: true