search_space:
  Architecture.parameters.n_estimators:
    type: int
    low: 500
    high: 3000
    step: 100
  Architecture.parameters.learning_rate:
    type: float
    low: 0.001
    high: 0.1
    log: true
  Architecture.parameters.max_depth:
    type: int
    low: 3
    high: 10
  Architecture.parameters.subsample:
    type: float
    low: 0.5
    high: 1.0
  Architecture.parameters.colsample_bytree:
    type: float
    low: 0.5
    high: 1.0
  Architecture.parameters.reg_lambda:
    type: float
    low: 0.01
    high: 10.0
    log: true