experiment_type: tree
Architecture:
  class: CatBoostRegressor
  parameters:
    iterations: 2700
    learning_rate: 0.08414601207141828
    depth: 9
    l2_leaf_reg: 4.8548167643277464
    loss_function: RMSE
    verbose: 100
    allow_writing_files: False
Training:
  seed: 42
  dataset_id: BeijingPM10Quality
