experiment_type: nn
Architecture:
  class: MLP
  parameters:
    output_size: 1
    num_hidden_layers: 2
    hidden_dim: 512
    dropout_hidden: 0.0365863670171143
Training:
  seed: 42
  dataset_id: BeijingPM10Quality
  dataset_class: FlattenedDataset
  batch_size: 256
  num_epochs: 100
  optimizer: Adam
  optimizer_params:
    lr: 0.009069695421897365
  loss_function: MSELoss
