experiment_type: nn
Architecture:
  class: ResNet1D
  parameters:
    output_size: 1
    num_filters: 156
    fc_units: 512
    num_res_blocks: 4
    dropout1: 0.15361653647417456
    dropout2: 0.028091835356764717
Training:
  seed: 42
  dataset_id: BeijingPM10Quality
  dataset_class: SequentialDataset
  batch_size: 256
  num_epochs: 100
  optimizer: Adam
  optimizer_params:
    lr: 0.005844792348623777
  loss_function: MSELoss
