experiment_type: nn
Architecture:
  class: MLP
  parameters:
    output_size: 1
    num_hidden_layers: 1
    hidden_dim: 128
    dropout_hidden: 0.015202897336132627
Training:
  seed: 42
  dataset_id: TennesseeEastmanProcess
  dataset_class: FlattenedDataset
  batch_size: 256
  num_epochs: 100
  optimizer: Adam
  optimizer_params:
    lr: 0.004273246064610722
  loss_function: MSELoss