experiment_type: nn
Architecture:
  class: ResNet1D
  parameters:
    output_size: 1
    num_filters: 256
    fc_units: 256
    num_res_blocks: 4
    dropout1: 0.09323492210214082
    dropout2: 0.09481653981230842
Training:
  seed: 42
  dataset_id: TennesseeEastmanProcess
  dataset_class: SequentialDataset
  batch_size: 256
  num_epochs: 100
  optimizer: Adam
  optimizer_params:
    lr: 0.008759895239957191
  loss_function: MSELoss