experiment_type: tree
Architecture:
  class: CatBoostRegressor
  parameters:
    iterations: 2900
    learning_rate: 0.052059181915478134
    depth: 10
    l2_leaf_reg: 3.518264094396101
    loss_function: RMSE
    verbose: 100
    allow_writing_files: False
Training:
  seed: 42
  dataset_id: PPGDalia
