experiment_type: nn
Architecture:
  class: ResNet1D
  parameters:
    output_size: 1
    num_filters: 32
    fc_units: 512
    num_res_blocks: 4
    dropout1: 0.06006908207412925
    dropout2: 0.014102695604270259
Training:
  seed: 42
  dataset_id: "VehicleDynamicsDataset"
  dataset_class: SequentialDataset
  batch_size: 32
  num_epochs: 100
  optimizer: Adam
  optimizer_params:
    lr: 0.0014386496178753572
  loss_function: MSELoss
